# Generated by Django 4.1.1 on 2022-09-25 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('company_name', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=100)),
                ('proof_of_payment', models.CharField(max_length=100)),
                ('about_project', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unvetted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=120)),
                ('telegram_url', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
